name: Deploy Lambda Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    container:
      image: node:18.20.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Zip backend
        run: cd backend && zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          function_name: frenchifyApiProd
          zip_file: lambda.zip
